<?php

// +------------------------------------------------------------------------+
// | AuthPuppy Authentication Server                                        |
// | ===============================                                        |
// |                                                                        |
// | AuthPuppy is the new generation of authentication server for           |
// | a wifidog based captive portal suite                                   |
// +------------------------------------------------------------------------+
// | PHP version 5 required.                                                |
// +------------------------------------------------------------------------+
// | Homepage:     http://www.authpuppy.org/                                |
// | Launchpad:    http://www.launchpad.net/authpuppy                       |
// +------------------------------------------------------------------------+
// | This program is free software; you can redistribute it and/or modify   |
// | it under the terms of the GNU General Public License as published by   |
// | the Free Software Foundation; either version 2 of the License, or      |
// | (at your option) any later version.                                    |
// |                                                                        |
// | This program is distributed in the hope that it will be useful,        |
// | but WITHOUT ANY WARRANTY; without even the implied warranty of         |
// | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          |
// | GNU General Public License for more details.                           |
// |                                                                        |
// | You should have received a copy of the GNU General Public License along|
// | with this program; if not, write to the Free Software Foundation, Inc.,|
// | 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.            |
// +------------------------------------------------------------------------+


/**
 * BaseapPluginConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $pluginname
 * @property string $config_option
 * @property string $config_value
 * 
 * @method string         getPluginname()    Returns the current record's "pluginname" value
 * @method string         getConfigOption()  Returns the current record's "config_option" value
 * @method string         getConfigValue()   Returns the current record's "config_value" value
 * @method apPluginConfig setPluginname()    Sets the current record's "pluginname" value
 * @method apPluginConfig setConfigOption()  Sets the current record's "config_option" value
 * @method apPluginConfig setConfigValue()   Sets the current record's "config_value" value
 * 
 * @package    authpuppy
 * @author     Geneviève Bastien <gbastien@versatic.net>
 * @author     Philippe April <philippe@philippeapril.com>
 * @copyright  2010
 * @version    $Version: 0.1.0$
 */
abstract class BaseapPluginConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_plugin_config');
        $this->hasColumn('pluginname', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('config_option', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '250',
             ));
        $this->hasColumn('config_value', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}