<?php

// +------------------------------------------------------------------------+
// | AuthPuppy Authentication Server                                        |
// | ===============================                                        |
// |                                                                        |
// | AuthPuppy is the new generation of authentication server for           |
// | a wifidog based captive portal suite                                   |
// +------------------------------------------------------------------------+
// | PHP version 5 required.                                                |
// +------------------------------------------------------------------------+
// | Homepage:     http://www.authpuppy.org/                                |
// | Launchpad:    http://www.launchpad.net/authpuppy                       |
// +------------------------------------------------------------------------+
// | This program is free software; you can redistribute it and/or modify   |
// | it under the terms of the GNU General Public License as published by   |
// | the Free Software Foundation; either version 2 of the License, or      |
// | (at your option) any later version.                                    |
// |                                                                        |
// | This program is distributed in the hope that it will be useful,        |
// | but WITHOUT ANY WARRANTY; without even the implied warranty of         |
// | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          |
// | GNU General Public License for more details.                           |
// |                                                                        |
// | You should have received a copy of the GNU General Public License along|
// | with this program; if not, write to the Free Software Foundation, Inc.,|
// | 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.            |
// +------------------------------------------------------------------------+


/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Nodesforeignkey extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('connections', 'connections_node_id_nodes_id_1', array(
             'name' => 'connections_node_id_nodes_id_1',
             'local' => 'node_id',
             'foreign' => 'id',
             'foreignTable' => 'nodes',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('connections', 'connections_node_id', array(
             'fields' => 
             array(
              0 => 'node_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('connections', 'connections_node_id_nodes_id_1');
        $this->removeIndex('connections', 'connections_node_id', array(
             'fields' => 
             array(
              0 => 'node_id',
             ),
             ));
    }
}